export const SET_SIDEBAR_EXPANSION_STATE = 'SET_SIDEBAR_EXPANSION_STATE';

export const SET_SIDEBAR_PERSISTENT_EXPANSION_STATE =
  'SET_SIDEBAR_PERSISTENT_EXPANSION_STATE';

export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

export const REQUEST_COMMON_DATA = 'REQUEST_COMMON_DATA';
export const RECEIVE_COMMON_DATA = 'RECEIVE_COMMON_DATA';

export const REQUEST_NOTIFICATIONS = 'REQUEST_NOTIFICATIONS';
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS';

export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';

export const MARK_ALL_NOTIFICATIONS_AS_READ_START =
  'MARK_ALL_NOTIFICATIONS_AS_READ_START';
export const MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS =
  'MARK_ALL_NOTIFICATIONS_AS_READ_SUCCESS';

export const REQUEST_DASHBOARD_DATA = 'REQUEST_DASHBOARD_DATA';
export const RECEIVE_DASHBOARD_DATA = 'RECEIVE_DASHBOARD_DATA';

export const REQUEST_MEASUREMENTS = 'REQUEST_MEASUREMENTS';
export const RECEIVE_MEASUREMENTS = 'RECEIVE_MEASUREMENTS';

export const REQUEST_MEASUREMENT_ADDING = 'REQUEST_MEASUREMENT_ADDING';
export const HANDLE_MEASUREMENT_ADDING = 'HANDLE_MEASUREMENT_ADDING';

export const REQUEST_MEASUREMENT_REMOVAL = 'REQUEST_MEASUREMENT_REMOVAL';
export const REMOVE_MEASUREMENT = 'REMOVE_MEASUREMENT';

export const REQUEST_UNLOCKED_ACHIEVEMENTS = 'REQUEST_UNLOCKED_ACHIEVEMENTS';
export const RECEIVE_UNLOCKED_ACHIEVEMENTS = 'RECEIVE_UNLOCKED_ACHIEVEMENTS';

export const REQUEST_FAVORITE_ITEMS = 'REQUEST_FAVORITE_ITEMS';
export const RECEIVE_FAVORITE_ITEMS = 'RECEIVE_FAVORITE_ITEMS';

export const REQUEST_PREFERENCES = 'REQUEST_PREFERENCES';
export const RECEIVE_PREFERENCES = 'RECEIVE_PREFERENCES';

export const REQUEST_PREFERENCES_UPDATE = 'REQUEST_PREFERENCES_UPDATE';
export const HANDLE_PREFERENCES_UPDATE = 'HANDLE_PREFERENCES_UPDATE';

export const REQUEST_TRAINING_PLANS = 'REQUEST_TRAINING_PLANS';
export const RECEIVE_TRAINING_PLANS = 'RECEIVE_TRAINING_PLANS';

export const REQUEST_PARTIAL_COURSES = 'REQUEST_PARTIAL_COURSES';
export const RECEIVE_PARTIAL_COURSES = 'RECEIVE_PARTIAL_COURSES';

export const REQUEST_FULL_COURSES = 'REQUEST_FULL_COURSES';
export const RECEIVE_FULL_COURSES = 'RECEIVE_FULL_COURSES';

export const REQUEST_CURRENT_COURSES = 'REQUEST_CURRENT_COURSES';
export const RECEIVE_CURRENT_COURSES = 'RECEIVE_CURRENT_COURSES';

export const REQUEST_DAY_SCHEDULE = 'REQUEST_DAY_SCHEDULE';
export const RECEIVE_DAY_SCHEDULE = 'RECEIVE_DAY_SCHEDULE';

export const REQUEST_WEEK_SCHEDULE = 'REQUEST_WEEK_SCHEDULE';
export const RECEIVE_WEEK_SCHEDULE = 'RECEIVE_WEEK_SCHEDULE';

export const REQUEST_ALL_TRAINERS = 'REQUEST_ALL_TRAINERS';
export const RECEIVE_ALL_TRAINERS = 'RECEIVE_ALL_TRAINERS';

export const REQUEST_COURSE_FILTERS = 'REQUEST_COURSE_FILTERS';
export const RECEIVE_COURSE_FILTERS = 'RECEIVE_COURSE_FILTERS';

export const REQUEST_GOALS = 'REQUEST_GOALS';
export const RECEIVE_GOALS = 'RECEIVE_GOALS';

export const REQUEST_MEAL_CATEGORIES = 'REQUEST_MEAL_CATEGORIES';
export const RECEIVE_MEAL_CATEGORIES = 'RECEIVE_MEAL_CATEGORIES';

export const REQUEST_MEALS_CATEGORY_INFO = 'REQUEST_MEALS_CATEGORY_INFO';
export const RECEIVE_MEALS_CATEGORY_INFO = 'RECEIVE_MEALS_CATEGORY_INFO';

export const REQUEST_MEALS_CATEGORY_ITEMS = 'REQUEST_MEALS_CATEGORY_ITEMS';
export const RECEIVE_MEALS_CATEGORY_ITEMS = 'RECEIVE_MEALS_CATEGORY_ITEMS';

export const REQUEST_MEAL_SEARCH_RESULTS = 'REQUEST_MEAL_SEARCH_RESULTS';
export const RECEIVE_MEAL_SEARCH_RESULTS = 'RECEIVE_MEAL_SEARCH_RESULTS';

export const REQUEST_MEAL = 'REQUEST_MEAL';
export const RECEIVE_MEAL = 'RECEIVE_MEAL';

export const REQUEST_MEAL_PLAN = 'REQUEST_MEAL_PLAN';
export const RECEIVE_MEAL_PLAN = 'RECEIVE_MEAL_PLAN';

export const REQUEST_GROCERY_LIST = 'REQUEST_GROCERY_LIST';
export const RECEIVE_GROCERY_LIST = 'RECEIVE_GROCERY_LIST';

export const REQUEST_GROCERY_LIST_PDF = 'REQUEST_GROCERY_LIST_PDF';
export const RECEIVE_GROCERY_LIST_PDF = 'RECEIVE_GROCERY_LIST_PDF';

export const REQUEST_HEALTH_POSTS = 'REQUEST_HEALTH_POSTS';
export const RECEIVE_HEALTH_POSTS = 'RECEIVE_HEALTH_POSTS';

export const REQUEST_PUR_LIFE_POSTS = 'REQUEST_PUR_LIFE_POSTS';
export const RECEIVE_PUR_LIFE_POSTS = 'RECEIVE_PUR_LIFE_POSTS';

export const REQUEST_VIDEOS = 'REQUEST_VIDEOS';
export const RECEIVE_VIDEOS = 'RECEIVE_VIDEOS';

export const REQUEST_VIDEO = 'REQUEST_VIDEO';
export const RECEIVE_VIDEO = 'RECEIVE_VIDEO';

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';

export const REQUEST_COMMENT_CREATION = 'REQUEST_COMMENT_CREATION';
export const HANDLE_COMMENT_CREATION = 'HANDLE_COMMENT_CREATION';

export const REQUEST_COMMENT_UPDATE = 'REQUEST_COMMENT_UPDATE';
export const HANDLE_COMMENT_UPDATE = 'HANDLE_COMMENT_UPDATE';

export const REQUEST_COMMENT_DELETION = 'REQUEST_COMMENT_DELETION';
export const HANDLE_COMMENT_DELETION = 'HANDLE_COMMENT_DELETION';

export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';

export const ADD_FRIEND_START = 'ADD_FRIEND_START';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';

export const RECEIVE_REQUESTED_FRIENDS = 'RECEIVE_REQUESTED_FRIENDS';

export const REQUEST_FRIENDS_SEARCH_RESULTS = 'REQUEST_FRIENDS_SEARCH_RESULTS';
export const RECEIVE_FRIENDS_SEARCH_RESULTS = 'RECEIVE_FRIENDS_SEARCH_RESULTS';

export const REQUEST_FRIEND_REQUESTS = 'REQUEST_FRIEND_REQUESTS';
export const RECEIVE_FRIEND_REQUESTS = 'RECEIVE_FRIEND_REQUESTS';

export const REQUEST_FRIEND_REMOVAL = 'REQUEST_FRIEND_REMOVAL';
export const HANDLE_FRIEND_REMOVAL = 'HANDLE_FRIEND_REMOVAL';

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';

export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export const REJECT_FRIEND_REQUEST_SUCCESS = 'REJECT_FRIEND_REQUEST_SUCCESS';

export const REQUEST_FITBOOK_SIDEBAR_DATA = 'REQUEST_FITBOOK_SIDEBAR_DATA';
export const RECEIVE_FITBOOK_SIDEBAR_DATA = 'RECEIVE_FITBOOK_SIDEBAR_DATA';

export const ACCEPT_FITBOOK_USAGE = 'ACCEPT_FITBOOK_USAGE';
export const ACCEPT_FITBOOK_USAGE_SUCCESS = 'ACCEPT_FITBOOK_USAGE_SUCCESS';

export const REQUEST_PINNED_POST_LIKE = 'REQUEST_PINNED_POST_LIKE';
export const HANDLE_PINNED_POST_LIKE = 'HANDLE_PINNED_POST_LIKE';

export const REQUEST_PINNED_POST_UNLIKE = 'REQUEST_PINNED_POST_UNLIKE';
export const HANDLE_PINNED_POST_UNLIKE = 'HANDLE_PINNED_POST_UNLIKE';

export const REQUEST_ALL_FITBOOK_POSTS = 'REQUEST_ALL_FITBOOK_POSTS';
export const RECEIVE_ALL_FITBOOK_POSTS = 'RECEIVE_ALL_FITBOOK_POSTS';

export const REQUEST_VIDCOMMENTS_FITBOOK_POSTS =
  'REQUEST_VIDCOMMENTS_FITBOOK_POSTS';
export const RECEIVE_VIDCOMMENTS_FITBOOK_POSTS =
  'RECEIVE_VIDCOMMENTS_FITBOOK_POSTS';

export const REQUEST_FRIENDS_FITBOOK_POSTS = 'REQUEST_FRIENDS_FITBOOK_POSTS';
export const RECEIVE_FRIENDS_FITBOOK_POSTS = 'RECEIVE_FRIENDS_FITBOOK_POSTS';

export const REQUEST_TRAINER_FITBOOK_POSTS = 'REQUEST_TRAINER_FITBOOK_POSTS';
export const RECEIVE_TRAINER_FITBOOK_POSTS = 'RECEIVE_TRAINER_FITBOOK_POSTS';

export const REQUEST_FITBOOK_POST_LIKE = 'REQUEST_FITBOOK_POST_LIKE';
export const HANDLE_FITBOOK_POST_LIKE = 'HANDLE_FITBOOK_POST_LIKE';

export const REQUEST_FITBOOK_POST_UNLIKE = 'REQUEST_FITBOOK_POST_UNLIKE';
export const HANDLE_FITBOOK_POST_UNLIKE = 'HANDLE_FITBOOK_POST_UNLIKE';

export const REQUEST_POST_CREATION = 'REQUEST_POST_CREATION';
export const HANDLE_POST_CREATION = 'HANDLE_POST_CREATION';

export const REQUEST_POST_UPDATE = 'REQUEST_POST_UPDATE';
export const HANDLE_POST_UPDATE = 'HANDLE_POST_UPDATE';

export const REQUEST_POST_REMOVAL = 'REQUEST_POST_REMOVAL';
export const HANDLE_POST_REMOVAL = 'HANDLE_POST_REMOVAL';

export const REQUEST_POST_PIN = 'REQUEST_PIN_POST';
export const HANDLE_POST_PIN = 'HANDLE_PIN_POST';

export const REQUEST_POST_UNPIN = 'REQUEST_UNPIN_POST';
export const HANDLE_POST_UNPIN = 'HANDLE_UNPIN_POST';

export const REQUEST_PROFILE_DATA = 'REQUEST_PROFILE_DATA';
export const RECEIVE_PROFILE_DATA = 'RECEIVE_PROFILE_DATA';

export const REQUEST_FITBOOK_STATS = 'REQUEST_FITBOOK_STATS';
export const RECEIVE_FITBOOK_STATS = 'RECEIVE_FITBOOK_STATS';

export const REQUEST_FITBOOK_CHATS = 'REQUEST_FITBOOK_CHATS';
export const RECEIVE_FITBOOK_CHATS = 'RECEIVE_FITBOOK_CHATS';

export const REQUEST_FITBOOK_CHAT = 'REQUEST_FITBOOK_CHAT';
export const RECEIVE_FITBOOK_CHAT = 'RECEIVE_FITBOOK_CHAT';

export const ADD_CHAT_MESSAGE_START = 'ADD_CHAT_MESSAGE_START';

export const UPDATE_CHAT_NAME_START = 'UPDATE_CHAT_NAME_START';
export const UPDATE_CHAT_NAME_SUCCESS = 'UPDATE_CHAT_NAME_SUCCESS';

export const UPDATE_CHAT_USERS_START = 'UPDATE_CHAT_USERS_START';
export const UPDATE_CHAT_USERS_SUCCESS = 'UPDATE_CHAT_USERS_SUCCESS';

export const CREATE_SINGLE_CHAT_START = 'CREATE_SINGLE_CHAT_START';
export const CREATE_SINGLE_CHAT_SUCCESS = 'CREATE_SINGLE_CHAT_SUCCESS';

export const CREATE_GROUP_CHAT_START = 'CREATE_GROUP_CHAT_START';

export const RQUEST_REGISTRATION_USER = 'RQUEST_REGISTRATION_USER';
export const RECEIVE_REGISTRATION_USER = 'RECEIVE_REGISTRATION_USER';
export const RECEIVE_REGISTRATION_ERROR_MESSAGE_USER = 'RECEIVE_REGISTRATION_ERROR_MESSAGE_USER';
